 # Redirecionar envios para o endereço de e-mail usando o recurso de tratamento de formulários do Netlify.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
